version: '3.3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.uwsgi
    links:
    - rabbit
    - mysql
    ports:
    - 8050:8050
    environment:
      PEEWEE_ADDR: mysql
      BROKER_URL: pyamqp://guest:guest@rabbit:5672//

  backend:
    build:
      context: .
      dockerfile: Dockerfile.celery
    links:
     - rabbit
     - mysql
    environment:
      PEEWEE_ADDR: mysql
      BROKER_URL: pyamqp://guest:guest@rabbit:5672//

  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pacifica_dispatcher
      MYSQL_USER: dispatcher
      MYSQL_PASSWORD: dispatcher
    ports:
     - 3306:3306

  rabbit:
    image: rabbitmq
    ports:
     - 5672:5672
